const kits = [
{ id: "aromatouchdiff", name: "Kit Di Iscrizione Aromatouch Diffused", price: 190, type: ["oli"] },
{ id: "aromatrain", name: "Kit Training Aromatouch", price: 291, type: ["oli"] },
{ id: "essetouch", name: "Kit dōTERRA Essential Aromatics Touch", price: 134.75, type: ["oli"] },
{ id: "family", name: "Family Essentials Enrolment", price: 188, type: ["oli"] },
{ id: "home", name: "Kit Home Essentials", price: 336, type: ["oli"] },
{ id: "mood", name: "Kit Mood Management", price: 143, type: ["oli"] },
{ id: "yoga", name: "Yoga Collection", price: 69, type: ["oli"] },
{ id: "esse", name: "Sistema dōTERRA Essential Aromatics", price: 231, type: ["oli"] },
{ id: "kids", name: "Kid's Collection Enrolment", price: 152, type: ["oli"] },
{ id: "athlete", name: "Athlete's Care Kit", price: 199, type: ["oli", "integratori"] },
{ id: "together", name: "Kit dōTERRA Together", price: 399, type: ["oli"] },
{ id: "natural", name: "Kit Di Iscrizione Natural Solutions", price: 776, type: ["oli", "integratori"] },
{ id: "naturalveg", name: "Kit Di Iscrizione Natural Solutions con LLV Vegano", price: 860, type: ["oli", "integratori"] },
{ id: "season", name: "Kit Changing Season", price: 197, type: ["oli", "integratori"] },
{ id: "tummy", name: "Kit Tummy Support", price: 125, type: ["integratori"] },
{ id: "women", name: "Kit Women's Health", price: 88, type: ["integratori"] },
{ id: "llv", name: "dōTERRA Lifelong Vitality Pack", price: 108, type: ["integratori"] },
{ id: "llvveg", name: "dōTERRA Lifelong Vitality Pack Vegano", price: 108, type: ["integratori"] },
{ id: "restore", name: "Kit Di Iscrizione Cleanse & Restore", price: 287, type: ["integratori"] },
{ id: "restoreveg", name: "Kit Di Iscrizione Cleanse & Restore con LLV Vegano", price: 287, type: ["integratori"] },
];
